apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: adevinta-application
  namespace: prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: adevinta-application
  minReplicas: 1
  maxReplicas: 3